# nome da pipeline
name: 'Execucao agendada'

#regras de disparo(triggers)
on:
  #gatilho de agendamento: schedule
  #https://crontab.guru/#0_6_*_*_1
  #a - minuto
  #b - hora
  #c - dia do mês
  #d - mês
  #e - dia da semana
  #rodar o regressivo toda segunda-feira pela manhã
  #'cron'
  #a b c d e
  #0 6 * * 1
  schedule:
    - cron: '0 6 * * 1'

# trabalhos e tarefas dentor do pipeline: jobs
jobs:
  e2e-tests:
    # available images https://github.com/actions/runner-images
    # maquina que o job vai executar
    runs-on: ubuntu-latest

    #passos do script de build
    steps:
      #clone do projeto
      - uses: actions/checkout@v4

      #instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      #instalacao do yarn
      - name: Instalacao do Yarn
        run: npm install -g yarn

      #instalacao das dependencias
      - name: Instalacao das dependencias
        run: yarn

      #instalacao do playwright
      - name: Instalacao do playwright
        run: yarn playwright install

      #executar os testes E2E
      - name: Executando testes e2e
        run: yarn run e2e
