# nome da pipeline
name: 'playwright report'

#regras de disparo(triggers)
on: 
  #gatilho de execucao manual: workflow_dispatch
  workflow_dispatch:

# trabalhos e tarefas dentor do pipeline: jobs
jobs:
  e2e-tests:
    # available images https://github.com/actions/runner-images
    # maquina que o job vai executar
    runs-on: ubuntu-latest

    #passos do script de build
    steps:
      #clone do projeto
      - uses: actions/checkout@v4
        
      #instalacao do node
      - uses: actions/setup-node@v4
        with: 
          node-version: 22.x

      #instalacao do yarn
      - name: Instalacao do Yarn
        run: npm install -g yarn

      #instalacao das dependencias
      - name: Instalacao das dependencias
        run: yarn

      #instalacao do playwright
      - name: Instalacao do playwright
        run: yarn playwright install

      #executar os testes E2E
      - name: Executando testes e2e
        run: yarn run e2e

      - name: Publish Playwright Report
        uses: lohani-mohit/playwright-report-publisher@v1
        with:
          report-directory: "tests/playwright-report"
          environment: "dev"
          report-prefix: "e2e-tests"
          post-to: "both"
          working-directory: "tests"
          gcs-bucket: "my-playwright-reports"
          github-token: ${{ github.token }}
          gcp-sa-key: ${{ secrets.GCP_SA_KEY }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          test-status: ${{ steps.run-tests.outcome == 'success' && 'passed' || 'failed' }}